name: OSV Scanner

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]
  workflow_dispatch:
  schedule:
    - cron: "37 8 * * 1"

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  scan-pr:
    if: github.event_name == 'pull_request'
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@v2.3.5
    with:
      scan-args: |-
        --lockfile=pubspec.lock

  scan-main:
    if: github.event_name != 'pull_request'
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@v2.3.5
    with:
      scan-args: |-
        --lockfile=pubspec.lock
